/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaksi;

/**
 *
 * @author Rohim
 */
import java.awt.HeadlessException;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;


public class FormBarang extends javax.swing.JFrame {
    // class utama dari JFrame FormBarang, script ini cuma contoh untuk menandakan pengisian script dibawah class ini
    // Script variable statment
    /**
     * Creates new form FormBarang
     */
        Connection con = null;
	ResultSet rs = null;
	PreparedStatement pst = null;
	Statement statBrg;
	Boolean ada = false;
        
    
    public FormBarang() {
        initComponents();
        koneksi();   //memanggil fungsi koneksi
        display(); // menggil fungsi dislay untuk menampilkan data ke table
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        TSimpan = new javax.swing.JButton();
        TEdit = new javax.swing.JButton();
        THapus = new javax.swing.JButton();
        TClear = new javax.swing.JButton();
        TKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Input Barang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel2.setText("Kode Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setText("Harga Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 160, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, -1));

        TSimpan.setText("Simpan");
        TSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(TSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        TEdit.setText("Edit");
        TEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEditActionPerformed(evt);
            }
        });
        getContentPane().add(TEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        THapus.setText("Hapus");
        THapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THapusActionPerformed(evt);
            }
        });
        getContentPane().add(THapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        TClear.setText("Clear");
        TClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TClearActionPerformed(evt);
            }
        });
        getContentPane().add(TClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        TKeluar.setText("Keluar");
        TKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(TKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 470, 200));

        pack();
    }// </editor-fold>                        

    private void TSimpanActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        try{
            koneksi();
            statBrg = con.createStatement();
            String SQL = "insert into barang values('"+jTextField1.getText()+"','"+jTextField2.getText()+"','"+jTextField3.getText()+"')";
            statBrg.executeUpdate(SQL);
            display();
            statBrg.close();
            con.close();
            Clear();
            JOptionPane.showMessageDialog(null, "berhasil simpan");
            
        }catch(HeadlessException | SQLException exc){
            System.err.println(exc.getMessage());
        }
    }                                       

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        try {
            koneksi();
            int row =jTable1.getSelectedRow();
            String tabel_klik=(jTable1.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from barang where kode_barang='"+tabel_klik+"'");
            if(sql.next()){
                String id = sql.getString("kode_barang");
                jTextField1.setText(id);
                String nama = sql.getString("nama_barang");
                jTextField2.setText(nama);
                String harga = sql.getString("harga");
                jTextField3.setText(harga);
            }
        } catch (SQLException e) {}
        
    }                                    

    private void TEditActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
         try{
            koneksi();
            statBrg = con.createStatement();
            String SQL = "update barang SET kode_barang = '"+jTextField1.getText()+"', nama_barang = '"+jTextField2.getText()+"', harga = '"+jTextField3.getText()+"' WHERE kode_barang = '"+jTextField1.getText()+"'";
            statBrg.executeUpdate(SQL);
            display();
            statBrg.close();
            con.close();
            Clear();
            JOptionPane.showMessageDialog(null, "berhasil edit");
           
        }catch(HeadlessException | SQLException exc){
            System.err.println(exc.getMessage());
        }
    }                                     

    private void THapusActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        try{
            koneksi();
            statBrg = con.createStatement();
            String SQL = "DELETE FROM barang WHERE kode_barang = '"+jTextField1.getText()+"'";
            statBrg.executeUpdate(SQL);
            display();
            statBrg.close();
            con.close();
            JOptionPane.showMessageDialog(null, "berhasil hapus");
           
        }catch(HeadlessException | SQLException exc){
            System.err.println(exc.getMessage());
        }
    }                                      

    private void TClearActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        Clear();
    }                                      

    private void TKeluarActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        System.exit(0); // keluar
    }                                       

    /**
     * @param args the command line arguments
     */
    private void koneksi() {
	try{
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost/barang"; //url database
            String user="root"; //user database
            String pass=""; //password database
            con = DriverManager.getConnection(url,user,pass);
            statBrg = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs = statBrg.executeQuery("select * from barang");
            
            }catch(ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
                System.exit(0);
            }
    }
    
    private void display(){
        try{
            String sql="select * from barang";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
 }
    
    private void Clear(){
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
  }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormBarang().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton TClear;
    private javax.swing.JButton TEdit;
    private javax.swing.JButton THapus;
    private javax.swing.JButton TKeluar;
    private javax.swing.JButton TSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration                   
}
